const artist = [
    {
    "idArtist": "112557",
    "strArtist": "Alter Bridge",
    "strArtistStripped": null,
    "strArtistAlternate": "",
    "strLabel": null,
    "idLabel": null,
    "intFormedYear": "2004",
    "intBornYear": null,
    "intDiedYear": null,
    "strDisbanded": null,
    "strStyle": "Rock/Pop",
    "strGenre": "Hard Rock",
    "strMood": "",
    "strWebsite": "www.alterbridge.com",
    "strFacebook": "",
    "strTwitter": "",
    "strBiographyEN": "Alter Bridge is an American rock band that was formed in 2004 in Orlando, Florida. It consists of lead guitarist and backing vocalist Mark Tremonti, bassist Brian Marshall, and drummer Scott Phillips, all of whom are also members of Creed, alongside lead vocalist and rhythm guitarist Myles Kennedy, formerly of The Mayfield Four and the frontman of Slash's current solo project. Tremonti named the group after an actual bridge that used to be located in Grosse Pointe, Michigan, near his former home on Alter Road.\nDespite Creed's multi-platinum success, Alter Bridge arose with only gold status with their first studio album, One Day Remains, which was released on Wind-up Records in August 2004 to generally mixed reviews. After the band's first tour, they dropped their contract with Wind-up Records in 2006 and signed with Universal Republic Records, releasing their second album, Blackbird, which was positively received by critics, in October 2007. The band spent the next two years touring and working on other projects before reconvening in 2010 to work on their third album. Titled AB III, the album was released in October 2010 on Roadrunner Records and was a critical success. In January 2011, the band's first live album and concert film, Live from Amsterdam, was finally released in stores after two years of delays. A second concert film, Live at Wembley, was released in March 2012.\nDespite relatively low mainstream success and label support for the majority of the band's career, Alter Bridge's music has been critically successful, and the band has become known for its frequent, extensive touring and loyal fanbase. The individual members of Alter Bridge are also involved with various other projects, including solo and session work, Creed, and Kennedy's collaborations with Slash and former members of Led Zeppelin. In 2009, Ultimate Guitar Archive named Alter Bridge the 36th greatest band of the decade.",
    "strBiographyDE": null,
    "strBiographyFR": null,
    "strBiographyCN": null,
    "strBiographyIT": null,
    "strBiographyJP": null,
    "strBiographyRU": null,
    "strBiographyES": null,
    "strBiographyPT": null,
    "strBiographySE": null,
    "strBiographyNL": "Drie van de vier leden van deze band (gitarist Mark Tremonti, drummer Scott Philips en bassist Brian Marshall) zijn afkomstig van de band Creed. Myles Kennedy was de zanger/gitarist van de band The Mayfield Four. Waar Creed gezien werd als commerciële grunge, wordt Alter Bridge gezien als 'powerhouse-rock'. De band haalt haar invloeden uit bands zoals Led Zeppelin.\nMet de komst van zanger Kennedy heeft het Creed-trio het roer radicaal omgegooid en kiest het met Alter Bridge voor een veel moderner en heavieër geluid inclusief gitaarsolo's. Tremonti wordt als een echte 'old school' gitarist beschouwd. De band bracht een succesvol debuutalbum uit: One Day Remains.\nOm de band te introduceren speelde de band in Europa drie showcases. De tweede showcase was in De Melkweg in Amsterdam met in het voorprogramma Switchfoot. Oorspronkelijk zou labelgenoot Submersed ook optreden. Daarna kwamen ze terug met shows in Utrecht, Tilburg en Fields of Rock in Nijmegen. Tijdens hun Europese tournee in november 2005 kwamen ze in Nederland om in Paradiso op te treden. In het voorprogramma zat de band Logan. Op 9 oktober 2007 kwam Blackbird, het tweede album van Alter Bridge uit. Ook toerde de band weer door Europa en de Verenigde staten. Het daaropstaande Watch Over You, een rockballad, deed het goed in de Verenigde Staten.In 2010 werd het derde album \"AB III\"uitgebracht. Door deze cd's werd het stemgeluid van Myles Kennedy bij ex-Guns 'n' Roses gitarist Slash onder de aandacht gebracht,die hem aantrok als vaste zanger van zijn sologroep Slash.Myles Kennedy blijft echter ook actief bij Alter Bridge. In 2013 kwam het vierde album Fortress uit, terwijl de vijfde productie The Last Hero in 2016 is verschenen.",
    "strBiographyHU": null,
    "strBiographyNO": null,
    "strBiographyIL": null,
    "strBiographyPL": null,
    "strGender": "Male",
    "intMembers": "4",
    "strCountry": "Orlando, Florida, USA",
    "strCountryCode": "US",
    "strArtistThumb": "https://www.theaudiodb.com/images/media/artist/thumb/alter-bridge-4fd83896d6ec9.jpg",
    "strArtistLogo": "https://www.theaudiodb.com/images/media/artist/logo/alter-bridge-4dfb770ccd14f.png",
    "strArtistClearart": null,
    "strArtistWideThumb": "https://www.theaudiodb.com/images/media/artist/widethumb/ryvvrw1571077706.jpg",
    "strArtistFanart": "https://www.theaudiodb.com/images/media/artist/fanart/alter-bridge-4e27c6d626deb.jpg",
    "strArtistFanart2": "https://www.theaudiodb.com/images/media/artist/fanart/alter-bridge-4ecc0bb7bb08d.jpg",
    "strArtistFanart3": "https://www.theaudiodb.com/images/media/artist/fanart/alter-bridge-4ecc0bc7b5279.jpg",
    "strArtistFanart4": null,
    "strArtistBanner": "https://www.theaudiodb.com/images/media/artist/banner/xpspwp1348153299.jpg",
    "strMusicBrainzID": "60a23fda-a440-4ab9-a344-7dfdd2ed341a",
    "strISNIcode": null,
    "strLastFMChart": null,
    "intCharted": "4",
    "strLocked": "unlocked"
    }
    ];
const data = [
{
"idAlbum": 0,
"idArtist": "112557",
"idLabel": null,
"strAlbum": "One Day Remains",
"strAlbumStripped": "One Day Remains",
"strArtist": "Alter Bridge",
"strArtistStripped": "Alter Bridge",
"intYearReleased": "2004",
"strStyle": "Rock/Pop",
"strGenre": "Hard Rock",
"strLabel": null,
"strReleaseFormat": "Album",
"intSales": "0",
"strAlbumThumb": "https://www.theaudiodb.com/images/media/album/thumb/rrqwrx1366547012.jpg",
"strAlbumThumbHQ": null,
"strAlbumThumbBack": "https://www.theaudiodb.com/images/media/album/thumbback/8pk96x1620330250.jpg",
"strAlbumCDart": "https://www.theaudiodb.com/images/media/album/cdart/one-day-remains-4e9a01138cc8a.png",
"strAlbumSpine": null,
"strAlbum3DCase": null,
"strAlbum3DFlat": null,
"strAlbum3DFace": null,
"strAlbum3DThumb": null,
"strDescriptionEN": "One Day Remains is the debut studio album by the American rock band Alter Bridge, released on August 10, 2004 on Wind-up Records. The album was produced by Ben Grosse. It has been certified Gold in the United States with worldwide sales reaching 750,000. It is said the album received its name from the band members' attitudes that life should be lived as if only one day remains. Guitarist Mark Tremonti also said in an interview that the title is a reference to the title cards that appeared in the movie Donnie Darko, and it is one of the names the band considered using before settling with Alter Bridge.",
"strDescriptionDE": null,
"strDescriptionFR": null,
"strDescriptionCN": null,
"strDescriptionIT": null,
"strDescriptionJP": null,
"strDescriptionRU": null,
"strDescriptionES": null,
"strDescriptionPT": null,
"strDescriptionSE": null,
"strDescriptionNL": null,
"strDescriptionHU": null,
"strDescriptionNO": null,
"strDescriptionIL": null,
"strDescriptionPL": null,
"intLoved": null,
"intScore": null,
"intScoreVotes": null,
"strReview": "",
"strMood": "",
"strTheme": "",
"strSpeed": "Fast",
"strLocation": null,
"strMusicBrainzID": "23885e42-01ca-348b-81f9-b3077b3c8a5e",
"strMusicBrainzArtistID": "60a23fda-a440-4ab9-a344-7dfdd2ed341a",
"strAllMusicID": "mw0000701794",
"strBBCReviewID": null,
"strRateYourMusicID": "one_day_remains",
"strDiscogsID": "150614",
"strWikidataID": "Q1509690",
"strWikipediaID": "One_Day_Remains",
"strGeniusID": "One-day-remains",
"strLyricWikiID": null,
"strMusicMozID": null,
"strItunesID": null,
"strAmazonID": null,
"strLocked": "unlocked",
"track_listing":[
    " 1. Find the Real",
    " 2. One Day Remains",
    " 3. Open Your Eyes Flame icon",
    " 4. Burn It Down",
    " 5. Metalingus Flame icon",
    " 6. Broken Wings",
    " 7. In Loving Memory",
    " 8. Down to My Last",
    " 9. Watch Your Words",
    " 10. Shed My Skin",
    " 11. The End Is Here"
]
},
{
"idAlbum": 1,
"idArtist": "112557",
"idLabel": null,
"strAlbum": "Live at Wembley",
"strAlbumStripped": "Live at Wembley",
"strArtist": "Alter Bridge",
"strArtistStripped": "Alter Bridge",
"intYearReleased": "2012",
"strStyle": "Rock/Pop",
"strGenre": "Hard Rock",
"strLabel": null,
"strReleaseFormat": "Live",
"intSales": "0",
"strAlbumThumb": "https://www.theaudiodb.com/images/media/album/thumb/live-at-wembley-528f80b77a89f.jpg",
"strAlbumThumbHQ": null,
"strAlbumThumbBack": null,
"strAlbumCDart": "https://www.theaudiodb.com/images/media/album/cdart/live-at-wembley-52da471426631.png",
"strAlbumSpine": null,
"strAlbum3DCase": null,
"strAlbum3DFlat": null,
"strAlbum3DFace": null,
"strAlbum3DThumb": null,
"strDescriptionEN": "Alter Bridge: Live at Wembley – European Tour 2011 is the second concert film and live album by the rock band Alter Bridge. The DVD was filmed at the band's largest headline show at Wembley Arena on November 29, 2011, and was released worldwide on March 26, 2012. A 3D version was released in the summer of 2012 on Blu-ray and in select theaters. It is directed and produced by Daniel Catullo, who worked with the band on their first DVD, Live from Amsterdam. The official trailer for Live at Wembley was released on January 5, 2012. Singer Myles Kennedy dedicated the band's performance to the late Freddie Mercury.",
"strDescriptionDE": null,
"strDescriptionFR": null,
"strDescriptionCN": null,
"strDescriptionIT": null,
"strDescriptionJP": null,
"strDescriptionRU": null,
"strDescriptionES": null,
"strDescriptionPT": null,
"strDescriptionSE": null,
"strDescriptionNL": null,
"strDescriptionHU": null,
"strDescriptionNO": null,
"strDescriptionIL": null,
"strDescriptionPL": null,
"intLoved": null,
"intScore": null,
"intScoreVotes": null,
"strReview": "",
"strMood": "",
"strTheme": "",
"strSpeed": "Medium",
"strLocation": null,
"strMusicBrainzID": "246ba1ef-57c1-46ee-90a6-3187b2e10e2f",
"strMusicBrainzArtistID": "60a23fda-a440-4ab9-a344-7dfdd2ed341a",
"strAllMusicID": null,
"strBBCReviewID": null,
"strRateYourMusicID": null,
"strDiscogsID": null,
"strWikidataID": "Q1032371",
"strWikipediaID": "Alter_Bridge:_Live_at_Wembley",
"strGeniusID": null,
"strLyricWikiID": null,
"strMusicMozID": null,
"strItunesID": null,
"strAmazonID": null,
"strLocked": "unlocked",
"track_listing":[
    " 1. Slip to the Void",
    " 2. Find the Real",
    " 3. Ghosts of Days Gone By",
    " 4. Come to Life",
    " 5. All Hope Is Gone",
    " 6. Metalingus",
    " 7. I Know It Hurts",
    " 8. Coeur d'Alene",
    " 9. Blackbird",
    " 10. Wonderful Life",
    " 11. Watch Over You",
    " 12. Ties That Bind",
    " 13. Isolation",
    " 14. Rise Today"
]
},
{
"idAlbum": 2,
"idArtist": "112557",
"idLabel": "45445",
"strAlbum": "AB III",
"strAlbumStripped": "AB III",
"strArtist": "Alter Bridge",
"strArtistStripped": "Alter Bridge",
"intYearReleased": "2010",
"strStyle": "Rock/Pop",
"strGenre": "Hard Rock",
"strLabel": "Roadrunner Records",
"strReleaseFormat": "Album",
"intSales": "0",
"strAlbumThumb": "https://www.theaudiodb.com/images/media/album/thumb/ab-iii-4e9a00e7e61dd.jpg",
"strAlbumThumbHQ": null,
"strAlbumThumbBack": "https://www.theaudiodb.com/images/media/album/thumbback/nmvldi1620330545.jpg",
"strAlbumCDart": "https://www.theaudiodb.com/images/media/album/cdart/ab-iii-545939eee75e8.png",
"strAlbumSpine": null,
"strAlbum3DCase": null,
"strAlbum3DFlat": null,
"strAlbum3DFace": null,
"strAlbum3DThumb": null,
"strDescriptionEN": "AB III is the third studio album by the rock band Alter Bridge, released on October 8, 2010 on the Roadrunner label.\n Produced by Michael \"Elvis\" Baskette, the album is a departure from the band's first two albums, lyrically because it is a loose concept album dealing with darker lyrical themes of struggling with faith, and musically due to its more dynamic and progressive sound. AB III is also the first Alter Bridge album to be released on Roadrunner Records, making it the band's third consecutive album to be released on a different label. The album was released on Roadrunner Records worldwide except North America, where it was self-released on Alter Bridge Recordings via Capitol Records.\n\nThe first single off the album, \"Isolation,\" is the band's most successful single to date and was released on September 26, 2010 in the United Kingdom and November 9, 2010 in the United States. AB III is the band's most successful album to date and has received general acclaim from critics, most notably Artistdirect, who called it a \"masterpiece.",
"strDescriptionDE": null,
"strDescriptionFR": null,
"strDescriptionCN": null,
"strDescriptionIT": null,
"strDescriptionJP": null,
"strDescriptionRU": null,
"strDescriptionES": null,
"strDescriptionPT": null,
"strDescriptionSE": null,
"strDescriptionNL": null,
"strDescriptionHU": null,
"strDescriptionNO": null,
"strDescriptionIL": null,
"strDescriptionPL": null,
"intLoved": null,
"intScore": "7",
"intScoreVotes": "1",
"strReview": "",
"strMood": "",
"strTheme": "",
"strSpeed": "Fast",
"strLocation": null,
"strMusicBrainzID": "86bdae66-86c6-44cc-8651-27fe3f924160",
"strMusicBrainzArtistID": "60a23fda-a440-4ab9-a344-7dfdd2ed341a",
"strAllMusicID": null,
"strBBCReviewID": null,
"strRateYourMusicID": null,
"strDiscogsID": null,
"strWikidataID": "Q287807",
"strWikipediaID": "AB_III",
"strGeniusID": null,
"strLyricWikiID": null,
"strMusicMozID": null,
"strItunesID": null,
"strAmazonID": null,
"strLocked": "unlocked",
"track_listing":[
    " 1. Slip to the Void",
    " 2. Isolation",
    " 3. Ghost of Days Gone By",
    " 4. All Hope Is Gone",
    " 5. Still Remains",
    " 6. Make It Right",
    " 7. Wonderful Life",
    " 8. I Know It Hurts",
    " 9. Show Me a Sign",
    " 10. Fallout",
    " 11. Breathe Again",
    " 12. Coeur D'Alene",
    " 13. Life Must Go On",
    " 14. Words Darker Than Their Wings"
]
},
{
"idAlbum": 3,
"idArtist": "112557",
"idLabel": "45404",
"strAlbum": "Blackbird",
"strAlbumStripped": "Blackbird",
"strArtist": "Alter Bridge",
"strArtistStripped": "Alter Bridge",
"intYearReleased": "2007",
"strStyle": "Rock/Pop",
"strGenre": "Hard Rock",
"strLabel": "Universal Republic Records",
"strReleaseFormat": "Album",
"intSales": "227000",
"strAlbumThumb": "https://www.theaudiodb.com/images/media/album/thumb/blackbird-4ea1403987129.jpg",
"strAlbumThumbHQ": null,
"strAlbumThumbBack": "https://www.theaudiodb.com/images/media/album/thumbback/0zhh7d1620330330.jpg",
"strAlbumCDart": "https://www.theaudiodb.com/images/media/album/cdart/blackbird-4e9a01139d62d.png",
"strAlbumSpine": null,
"strAlbum3DCase": null,
"strAlbum3DFlat": null,
"strAlbum3DFace": null,
"strAlbum3DThumb": null,
"strDescriptionEN": "Blackbird is the second studio album by rock band Alter Bridge, released on October 9, 2007 through Universal Republic Records. The first single, \"Rise Today\", was released on July 30, 2007. The album peaked at number 13 on the Billboard 200, selling 47,000 copies in its first week on the charts. As of December 2008, Blackbird has sold 227,000 copies. Despite receiving poor marketing and generally low mainstream success, initial critical reception towards the album was mostly positive.",
"strDescriptionDE": null,
"strDescriptionFR": null,
"strDescriptionCN": null,
"strDescriptionIT": null,
"strDescriptionJP": null,
"strDescriptionRU": null,
"strDescriptionES": null,
"strDescriptionPT": null,
"strDescriptionSE": null,
"strDescriptionNL": null,
"strDescriptionHU": null,
"strDescriptionNO": null,
"strDescriptionIL": null,
"strDescriptionPL": null,
"intLoved": null,
"intScore": null,
"intScoreVotes": null,
"strReview": "",
"strMood": "",
"strTheme": "",
"strSpeed": "Fast",
"strLocation": null,
"strMusicBrainzID": "ae403b22-323c-36b7-9352-2bd597083545",
"strMusicBrainzArtistID": "60a23fda-a440-4ab9-a344-7dfdd2ed341a",
"strAllMusicID": "mw0000496924",
"strBBCReviewID": null,
"strRateYourMusicID": "blackbird",
"strDiscogsID": "238749",
"strWikidataID": "Q880708",
"strWikipediaID": "Blackbird_(Alter_Bridge_album)",
"strGeniusID": null,
"strLyricWikiID": null,
"strMusicMozID": null,
"strItunesID": null,
"strAmazonID": null,
"strLocked": "unlocked",
"track_listing": [
    " 1. Ties That Bind",
    " 2. Come to Life",
    " 3. Brand New Start",
    " 4. Buried Alive",
    " 5. Coming Home",
    " 6. Before Tomorrow Comes",
    " 7. Rise Today",
    " 8. Blackbird",
    " 9. One by One",
    " 10. Watch Over You",
    " 11. Break Me Down",
    " 12. White Knuckles",
    " 13. Wayward One"
]
},
{
"idAlbum": 4,
"idArtist": "112557",
"idLabel": "45445",
"strAlbum": "Fortress",
"strAlbumStripped": "Fortress",
"strArtist": "Alter Bridge",
"strArtistStripped": "Alter Bridge",
"intYearReleased": "2013",
"strStyle": "Rock/Pop",
"strGenre": "Hard Rock",
"strLabel": "Roadrunner Records",
"strReleaseFormat": "Album",
"intSales": "0",
"strAlbumThumb": "https://www.theaudiodb.com/images/media/album/thumb/twyuup1383963096.jpg",
"strAlbumThumbHQ": null,
"strAlbumThumbBack": "https://www.theaudiodb.com/images/media/album/thumbback/yk4qm21620331084.jpg",
"strAlbumCDart": "https://www.theaudiodb.com/images/media/album/cdart/fortress-545939eee7c80.png",
"strAlbumSpine": null,
"strAlbum3DCase": null,
"strAlbum3DFlat": null,
"strAlbum3DFace": null,
"strAlbum3DThumb": null,
"strDescriptionEN": "Fortress is the fourth studio album by the rock band Alter Bridge, released by Roadrunner Records on September 25, 2013. Michael \"Elvis\" Baskette, who produced Alter Bridge's previous two albums, Blackbird and AB III, returns as producer. It will be released by Roadrunner Records worldwide except in the United States, where it will be self-released on October 8, 2013, through EMI. The lead single, \"Addicted to Pain\", was released on August 12, 2013. Fortress was recorded between April 26 and July 2, 2013 at Studio Barbarosa in Orlando, Florida. The album was written over the three previous years while the band toured, as well as during Alter Bridge's hiatus due to singer Myles Kennedy touring with Slash, guitarist Mark Tremonti releasing his debut solo album All I Was, and drummer Scott Phillips recording with his band Projected. Later in the month, Tremonti announced the band had approved the cover art and had mastered the new album.\n\nIn July, in an interview with MusicRadar.com Tremonti revealed that he would sing lead vocals on one track called \"The Waters Rise\", which appears on the album as \"Waters Rising\". The official track listing and cover art for Fortress was revealed on July 31, 2013 along with the track listing, consisting of 12 songs. The artwork was designed by Dan Tremonti.\n\nOn August 4, the cover art for the lead single \"Addicted to Pain\" was revealed, and a day later the band confirmed that the lead single \"Addicted to Pain\" would be released on August 12, in Europe, and on August 20, in the US. The single was made available for streaming a few days before release. On September 5, the official video for \"Addicted to Pain\" was released. The official video was shot by award-winning director Dan Catullo. On September 23, the band streamed the album in its entirety for a limited time on the Metal Hammer website as a UK exclusive.",
"strDescriptionDE": null,
"strDescriptionFR": null,
"strDescriptionCN": null,
"strDescriptionIT": null,
"strDescriptionJP": null,
"strDescriptionRU": null,
"strDescriptionES": null,
"strDescriptionPT": null,
"strDescriptionSE": null,
"strDescriptionNL": null,
"strDescriptionHU": null,
"strDescriptionNO": null,
"strDescriptionIL": null,
"strDescriptionPL": null,
"intLoved": null,
"intScore": "8.5",
"intScoreVotes": "2",
"strReview": "",
"strMood": "",
"strTheme": "",
"strSpeed": "Medium",
"strLocation": null,
"strMusicBrainzID": "d49ad853-5ca1-4cbb-a6b9-90f358239829",
"strMusicBrainzArtistID": "60a23fda-a440-4ab9-a344-7dfdd2ed341a",
"strAllMusicID": "mw0002569317",
"strBBCReviewID": null,
"strRateYourMusicID": null,
"strDiscogsID": "604216",
"strWikidataID": "Q14404733",
"strWikipediaID": "Fortress_(Alter_Bridge_album)",
"strGeniusID": null,
"strLyricWikiID": null,
"strMusicMozID": null,
"strItunesID": null,
"strAmazonID": null,
"strLocked": "unlocked",
"track_listing": [
    " 1. Cry of Achilles",
    " 2. Addicted To Pain",
    " 3. Bleed It Dry",
    " 4. Lover",
    " 5. The Uninvited",
    " 6. Peace Is Broken",
    " 7. Calm the Fire",
    " 8. Waters Rising",
    " 9. Farther Than the Sun",
    " 10. Cry a River",
    " 11. All Ends Well",
    " 12. Fortress"
]
},
{
"idAlbum": 5,
"idArtist": "112557",
"idLabel": "44906",
"strAlbum": "The Last Hero",
"strAlbumStripped": "The Last Hero",
"strArtist": "Alter Bridge",
"strArtistStripped": "Alter Bridge",
"intYearReleased": "2016",
"strStyle": "Rock/Pop",
"strGenre": "Hard Rock",
"strLabel": "Napalm Records",
"strReleaseFormat": "Album",
"intSales": "0",
"strAlbumThumb": "https://www.theaudiodb.com/images/media/album/thumb/rwpwuu1474776755.jpg",
"strAlbumThumbHQ": null,
"strAlbumThumbBack": "https://www.theaudiodb.com/images/media/album/thumbback/1jk6we1620331244.jpg",
"strAlbumCDart": "https://www.theaudiodb.com/images/media/album/cdart/e1oxb71599375294.png",
"strAlbumSpine": null,
"strAlbum3DCase": "https://www.theaudiodb.com/images/media/album/3dcase/ctfecn1599375308.png",
"strAlbum3DFlat": "https://www.theaudiodb.com/images/media/album/3dflat/g89cxb1599375323.png",
"strAlbum3DFace": "https://www.theaudiodb.com/images/media/album/3dface/r8zg3k1599375316.png",
"strAlbum3DThumb": "https://www.theaudiodb.com/images/media/album/3dthumb/bts1451599375664.png",
"strDescriptionEN": "The Last Hero is the fifth studio album by the American rock band Alter Bridge, released on October 7, 2016, by Napalm Records worldwide except in North America, where it was released on the band's own vanity label. It was produced by longtime collaborator Michael \"Elvis\" Baskette. The album's first single, \"Show Me a Leader\", was released digitally and to rock radio on July 26, 2016.",
"strDescriptionDE": null,
"strDescriptionFR": null,
"strDescriptionCN": null,
"strDescriptionIT": null,
"strDescriptionJP": null,
"strDescriptionRU": null,
"strDescriptionES": null,
"strDescriptionPT": null,
"strDescriptionSE": null,
"strDescriptionNL": null,
"strDescriptionHU": null,
"strDescriptionNO": null,
"strDescriptionIL": null,
"strDescriptionPL": null,
"intLoved": "1",
"intScore": "7.8",
"intScoreVotes": "5",
"strReview": "",
"strMood": "Energetic",
"strTheme": "",
"strSpeed": "Medium",
"strLocation": null,
"strMusicBrainzID": "03b56aa5-cbae-4b93-ae79-082d1110ebe3",
"strMusicBrainzArtistID": "60a23fda-a440-4ab9-a344-7dfdd2ed341a",
"strAllMusicID": "mw0002967928",
"strBBCReviewID": null,
"strRateYourMusicID": null,
"strDiscogsID": null,
"strWikidataID": null,
"strWikipediaID": "The_Last_Hero_(album)",
"strGeniusID": null,
"strLyricWikiID": null,
"strMusicMozID": null,
"strItunesID": null,
"strAmazonID": null,
"strLocked": "unlocked",
"track_listing": [
    " 1. Show Me a Leader",
    " 2. The Writing on the Wall",
    " 3. The Other Side",
    " 4. My Champion",
    " 5. Poison in Your Vains",
    " 6. Cradle to the Grave",
    " 7. Losing Patience",
    " 8. This Side of Fate",
    " 9. You Will Be Remembered",
    " 10. Crows on a Wire",
    " 11. Twillight",
    " 12. Island of Fools",
    " 13. The Last Hero",
    " 14. Last of Our Kind"
]
},
{
"idAlbum": 6,
"idArtist": "112557",
"idLabel": "44906",
"strAlbum": "Walk the Sky",
"strAlbumStripped": "Walk the Sky",
"strArtist": "Alter Bridge",
"strArtistStripped": "Alter Bridge",
"intYearReleased": "2019",
"strStyle": "",
"strGenre": "Hard Rock",
"strLabel": "Napalm Records",
"strReleaseFormat": "Album",
"intSales": "0",
"strAlbumThumb": "https://www.theaudiodb.com/images/media/album/thumb/yqsxvw1571077569.jpg",
"strAlbumThumbHQ": null,
"strAlbumThumbBack": "https://www.theaudiodb.com/images/media/album/thumbback/c1gu211620331391.jpg",
"strAlbumCDart": "https://www.theaudiodb.com/images/media/album/cdart/o00ieg1620331596.png",
"strAlbumSpine": null,
"strAlbum3DCase": "https://www.theaudiodb.com/images/media/album/3dcase/tqpurx1571580034.png",
"strAlbum3DFlat": null,
"strAlbum3DFace": null,
"strAlbum3DThumb": "https://www.theaudiodb.com/images/media/album/3dthumb/swpxyu1571580044.png",
"strDescriptionEN": "\"Walk the Sky\"  is the sixth studio album by American rock band Alter Bridge, released on October 18, 2019 on the Napalm Records label. It was produced by their longtime collaborator Michael Baskette, who has produced all of the band's albums since Blackbird.",
"strDescriptionDE": null,
"strDescriptionFR": null,
"strDescriptionCN": null,
"strDescriptionIT": null,
"strDescriptionJP": null,
"strDescriptionRU": null,
"strDescriptionES": null,
"strDescriptionPT": null,
"strDescriptionSE": null,
"strDescriptionNL": null,
"strDescriptionHU": null,
"strDescriptionNO": null,
"strDescriptionIL": null,
"strDescriptionPL": null,
"intLoved": null,
"intScore": null,
"intScoreVotes": null,
"strReview": "For over fifteen years, Alter Bridge have blurred the lines between Hard Rock and Heavy Metal, creating a unique space all of their own. If the band’s last studio album, 2016’s ‘The Last Hero’, tipped closer to Hard Rock, their refreshing new opus ‘Walk The Sky’ walks a finer tightrope, balanced precariously between a rock and the bands heavier side. If some would have delighted in another fourteen song album of more quintessential Alter Bridge, others yearned for a stirring of the pot. Well, with ‘Walk The Sky’, their sixth studio effort, the pot does indeed get stirred, producing some thrilling results.\nAlthough you wouldn’t have guessed it based on the record’s leading singles. “Wouldn’t You Rather”, with its spitfire delivery and heavy instrumentation, so dense it’s almost impenetrable, made for a curious first offering by suggesting an entirely heavier direction. Indeed, the semi symphonic metal “Pay No Mind,” and the crushing “Take The Crown,” would also suggest Alter Bridge have simply swung to the other side of the pendulum, gearing up to deliver a heavier ‘The Last Hero.’ That is until in the brilliant, epic, and stunning anthem that is “Godspeed”.\n To critique “Godspeed” with anything other than unconditional commendation would be inexcusable. From its initial, imminently addictive opening piano/synth hook, to its explosive main riff and emotive verses, by the time Myles Kennedy delivers the ascending pre-chorus before launching you into a chorus too good not to adore, “Godspeed” has comfortably established itself as the albums best track. In fact, it holds its own among the bands best across their entire catalog. It is simply that good.\n  If suspicions were beginning to brew that Alter Bridge had become a formulaic outfit, these speculations meet their end with this synth-based, modern rock classic that explores some new and exciting heavier territories for the band. Ambitious, adventurous and unmistakably alive, ‘Walk The Sky’ might well redefine what quintessential Alter Bridge sounds like.\nReviewed by Carl O'Rourke for metalwani.com.",
"strMood": "",
"strTheme": "",
"strSpeed": "Medium",
"strLocation": null,
"strMusicBrainzID": "2d0bf0b1-b1c9-4163-ae4e-830d2395aaf9",
"strMusicBrainzArtistID": "60a23fda-a440-4ab9-a344-7dfdd2ed341a",
"strAllMusicID": null,
"strBBCReviewID": null,
"strRateYourMusicID": null,
"strDiscogsID": null,
"strWikidataID": null,
"strWikipediaID": null,
"strGeniusID": null,
"strLyricWikiID": null,
"strMusicMozID": null,
"strItunesID": null,
"strAmazonID": null,
"strLocked": "unlocked",
"track_listing": [
    " 1. One Life",
    " 2. Wouldn't You Rather",
    " 3. In the Deep",
    " 4. Godspeed",
    " 5. Native Son",
    " 6. Take the Crown",
    " 7. Indoctrination",
    " 8. The Bitter End",
    " 9. Pay No Mind",
    " 10. Forever Falling",
    " 11. Clear Horizon",
    " 12. Walking on the Sky",
    " 13. Tear Us Apart",
    " 14. Dying Light"
]
}
];

let nav = `
    <ul><b>Alter Bridge Discography</b>
    <li><a href="/artist/0">One Day Remains</a></li>
    <li><a href="/artist/1">Live at Wembley</a></li>
    <li><a href="/artist/2">AB III</a></li>
    <li><a href="/artist/3">Blackbird</a></li>
    <li><a href="/artist/4">Fortress</a></li>
    <li><a href="/artist/5">The Last Hero</a></li>
    <li><a href="/artist/6">Walk The Sky</a></li>
    </ul>
`

const express = require('express');

const app = express();

let port = 3000;

app.get('/', (request, response)=>{

    response.send(`<img src="${artist[0].strArtistLogo}" height="200px">
    <div>
    <a href="/artist/0">
    <img src="${artist[0].strArtistThumb}" height="300px">
    </a>
    </div>
    <p>${artist[0].strBiographyEN}</p>`
    )
});

app.get('/artist/:id', (request, res) => {
    
    let id = request.params.id;

    res.send(`
        ${nav}
    
        <h1>${data[id].strAlbum}</h1>
        <img src="${data[id].strAlbumThumb}"  height="300px">
        <ol><b>Track Listing</b></ol>
        <p>${data[id].track_listing}</p>
        <p><a href="/">Homepage</a></p>
        
    
    `)

})

app.listen(port, ()=>{
    console.log(`Server is running on port ${port}`)
});